basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /health_check:
    get:
      description: health check
      operationId: health-check
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health Check
  /house:
    get:
      consumes:
      - application/json
      description: get all houses
      operationId: get-all-houses
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Get mocked houses
  /user:
    get:
      consumes:
      - application/json
      description: get all users
      operationId: get-all-users
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Get mocked users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
